stages:
  clean_data:
    cmd: python src/clean_data.py
    deps:
      - data/raw/Datos_2024_205.xlsx
      - src/clean_data.py
    outs:
      - data/clean/chagas_clean.csv

  prepare_data:
    cmd: python src/prepare_data.py
    deps:
      - data/clean/chagas_clean.csv
      - src/prepare_data.py
    outs:
      - data/clean/chagas_prepared.csv

  calibrate_seir:
    cmd: python src/calibrate_seir.py
    deps:
      - data/clean/chagas_prepared.csv
      - src/calibrate_seir.py
    outs:
      - models/seir_params.json
      - reports/seir_simulation.csv

  compute_lyapunov:
    cmd: python src/compute_lyapunov.py
    deps:
      - data/clean/chagas_prepared.csv
      - models/seir_params.json
      - src/compute_lyapunov.py
    outs:
      - models/lyapunov_valledupar.json